### ISSUE TITLE
Suggestion / Question :: update / delete before and after

### ISSUE THREAD

**Issue by jamespsterling** [dan-da/cdc_audit#2]
Have you thought about differentiating between the before update and after update column changes? I'm thinking the audit would be more valuable if you knew what the column values were changed from...

Overall though, amazing project! Love the ease of generating audit tables on the fly.

**Comment by dan-da** [comment]
You can already know what the column values were changed from.   You only need to look at the previous row with the same source-table primary key.

I'm not sure I understand your meaning with regards to using a before trigger.

If you are wanting both old and new values stored in the same row in the audit table, that could be accomplished with only an AFTER trigger.  Because the trigger has access to the OLD row and the NEW row.

A big disadvantage to doing that is data duplication and disk space.  Twice the amount of space would be required for the data columns of each row.  For very large tables such as often used in a data warehouse, this is an important consideration.  For small tables, not so much.

Another possible issue arises around the max column length.   The most obvious approach would be prefix "old_" to each column representing the previous values.  But if the original column name is already at or near the max colname length, then the prefixed column name would be invalid.  Workarounds are possible, but it is a bit gross.

I'll think about it some more, and keep this open meanwhile.   It could be implemented as an option, so that either audit table style could be used.

Do you have a particular use case in mind?

**Comment by jamespsterling** [comment]
I've been thinking about it wrong, I do know the before and after states, even the history. I just have to compare the primary table's active record with the audit table's last actionable record to get the field/column delta. For some reason I was hung up on this, but then it hit me like... doh!

**Comment by dan-da** [comment]
The audit table should always be synced with the primary table.  So the latest change is the delta between row N-1 and row N in the audit table where N is the latest row.   Second latest change is N-2 to N-1. etc.

Or latest change could be obtained via N-1 compared to primary table.   I think this is what you are saying.

**Comment by jamespsterling** [comment]
yup yup

**Comment by dbanet** [comment]
Shouldn't, indeed, the OLD value be stored in the UPDATE audit table?

https://stackoverflow.com/questions/28005200/creating-audit-trail-with-trigger-in-mysql#comment66372231_34104079

If cdc_audit is run on a non-empty table, then on first UPDATE of the source table, the old value would be lost to the update, since the NEW, not OLD value is written to the audit table.

Then, yes, indeed, to get the last delta, you would have to compare the last row of the audit table with the corresponding row of the source table.

**Comment by dbanet** [comment]
Additionally, [this](https://www.percona.com/blog/2008/09/29/why-audit-logging-with-triggers-in-mysql-is-bad-for-replication/).

**Comment by dan-da** [comment]
This code was written for brand new tables. When using existing tables with data i would suggest that the tool should automatically insert a row with the pre-existing data into the audit table at the time of audit table creation.  I would accept a pull request with this functionality if you wish to implement it.  Otherwise I will plan to add it when I can find a little time.

I see no need to use OLD during update trigger.
